[repository]
name = "sneridagh-dev"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "calver"
container_images_prefix = "ghcr.io/collective/sneridagh-dev-"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "sneridagh_dev"
path = "backend"
code_path = "src/sneridagh_dev"
changelog = "backend/CHANGELOG.md"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = false

[frontend.package]
name = "volto-sneridagh-dev"
path = "frontend/packages/volto-sneridagh-dev"
code_path = "src"
changelog = "frontend/packages/volto-sneridagh-dev/CHANGELOG.md"
towncrier_settings = "frontend/packages/volto-sneridagh-dev/towncrier.toml"
base_package = "@plone/volto"
publish = false

[cookieplone]
template = "project"
template_version = "6678734cc3713f3fab9ea510616cef59dc466514"
generated_date = "2026-06-12 20:51:55"
